# Repo Info
owner: josselinlbe
repo: upptime

# Sites to monitor
sites:
  - name: Piloterr
    url: https://piloterr.com

# Website Data
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: upptime.josselinlie.be
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitor
  introTitle: |
    Monitor of Josselin
  introMessage: |
    The following page shows current and recent uptime and outage statistics for application demos and docs sites.
    It's built using [upptime](https://github.com/upptime/upptime) and all checks are run via GitHub Actions.
  theme: ocean
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# CI Running Options
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/30 * * * *"

# See https://upptime.js.org/docs/configuration
